# Generated by Django 5.2.17 on 2026-09-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('kota', models.CharField(max_length=100)),
                ('provinsi', models.CharField(db_index=True, max_length=100)),
                ('kategori', models.CharField(db_index=True, max_length=50)),
                ('sub_kategori', models.CharField(blank=True, default='', max_length=100)),
                ('harga_tiket', models.IntegerField(db_index=True)),
                ('rating', models.FloatField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('fas_toilet', models.BooleanField(default=False)),
                ('fas_parkir', models.BooleanField(default=False)),
                ('fas_warung', models.BooleanField(default=False)),
                ('fas_mushola', models.BooleanField(default=False)),
                ('fas_penginapan', models.BooleanField(default=False)),
                ('tag_aktivitas', models.TextField(blank=True, default='')),
                ('cluster_label', models.CharField(blank=True, default='', max_length=100)),
                ('sumber_data', models.CharField(default='xlsx38', max_length=20)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('nama', 'kota'), name='uniq_nama_kota')],
            },
        ),
    ]
