# Generated by Django 5.2.17 on 2026-09-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JarakCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asal', models.CharField(max_length=100)),
                ('tujuan', models.CharField(max_length=100)),
                ('moda', models.CharField(default='mobil', max_length=20)),
                ('jarak_km', models.FloatField()),
                ('sumber', models.CharField(default='osrm', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('asal', 'tujuan', 'moda'), name='uniq_jarak_moda')],
            },
        ),
    ]
